# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/getting-started/configuration/
# -------------------------------------------------------------------------------------

title = "lpppp"
baseURL = "https://gongzhujiejie.github.io/"
# theme = "FixIt"
defaultContentLanguage = "zh-cn"
locale = "zh-CN"
languageName = "Chinese"
hasCJKLanguage = true
enableRobotsTXT = true
enableEmoji = true
mainSections = ["posts"]
enableGitInfo = true
relativeURLs = false
buildDrafts = false
summaryLength = 150
# ignore some build errors
ignoreLogs = [
  "error-get-remote-image",
  "error-get-remote-json",
  "error-remote-getjson",
  "error-missing-instagram-accesstoken"
]

[params]
  version = "0.3.X"
  description = "成功不是一种偶然，而是一种习惯。"
  keywords = ["Hugo", "FixIt"]
