# -------------------------------------------------------------------------------------
# Menu Configuration
# See: https://fixit.lruihao.cn/documentation/basics/#menu-configuration
# -------------------------------------------------------------------------------------

[[main]]
  identifier = "archives"
  parent = ""
  pre = ""
  post = ""
  name = "全部文章"
  url = "/archives/"
  title = ""
  weight = 1
  [main.params]
    class = ""
    draft = false
    icon = "fa-solid fa-archive"
    type = ""
    divided = false

[[main]]
  identifier = "categories"
  parent = ""
  pre = ""
  post = ""
  name = "分类"
  url = "/categories/"
  title = ""
  weight = 2
  [main.params]
    icon = "fa-solid fa-folder-tree"

[[main]]
  identifier = "tags"
  parent = ""
  pre = ""
  post = ""
  name = "标签"
  url = "/tags/"
  title = ""
  weight = 3
  [main.params]
    icon = "fa-solid fa-tags"

[[main]]
  identifier = "about"
  parent = ""
  pre = ""
  post = ""
  name = "about"
  url = "/about/"
  title = "about lpppp"
  weight = 5
  [main.params]
    icon = "fa-solid fa-user-astronaut"
